=== lincolnreese/JohnnyV/johnnyv/ext/Schema.json
{
  "$schema": "http://json-schema.org/schema#",

  "definitions": {
    "ssc32u":{
      "type": "object",
      "properties": {
                          "baud":           {
                                             "type": "integer",
                                             "enum": [9600,38400,115200]
                          },
                          "timeout":
                            {"anyOf": [
                                            {
                                             "type": "string",
                                             "enum": ["NONE"]
                                            },
                                            {
                                             "type": "integer",
                                             "enum": [0]
                                            },
                                            {
                                             "type": "number",
                                             "minimum": 0.1
                                            }
                            ]
                          },
                          "execution_time": {
                                             "type": "number",
                                             "minimum": 0

                          },
                          "voltage":        {
                                            "type": "number",
                                            "minimum": 7.4,
                                            "maximum": 11.1
                          }
      },
      "required": ["baud", "execution_time", "timeout", "voltage"]
    },

    "raspberrypi": {
      "type": "object",
      "properties": {
                          "ip":           {
                                            "type": "string",
                                            "format": "ip-address"
                          },
                          "username":     { "type": "string"},
                          "password":     { "type": "string"}
      },
      "required": ["ip", "username", "password"]
    },

    "components":{
      "type": "object",
      "patternProperties": {"^[a-z0-9]+((_)+[a-z0-9]+)*$":{"$ref": "#/definitions/component"}},
      "additionalProperties": false
    },

    "component": {
      "type": "object",
      "properties": {
                          "servo_list":  {"$ref": "#/definitions/servo_list"},
                          "motor_list":  {"$ref": "#/definitions/motor_list"}
      },
      "required": ["servo_list","motor_list"]
    },

    "servo_list": {
      "type": "object",
      "patternProperties": {"^[a-z0-9]+((_)+[a-z0-9]+)*$":{"$ref": "#/definitions/servo"}},
      "additionalProperties": false
    },

    "motor_list": {
      "type": "object",
      "patternProperties": {"^[a-z0-9]+((_)+[a-z0-9]+)*$":{"$ref": "#/definitions/motor"}},
      "additionalProperties": false
    },

    "servo": {
      "type": "object",
      "properties": {
                          "color_scheme":  {"type": "string"},
                          "dependencies":  {
                                            "type": "array",
                                            "items": {
                                                    "type": "number"
                                            }
                          },
                          "pin":           {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 31
                          },
                          "max_pulse":     {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 180
                          },
                          "min_pulse":     {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 180
                          },
                          "abs_max_pulse": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 180
                          },
                          "abs_min_pulse": {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 180
                          },
                          "pulse_width":   {"type": "integer"},
                          "init_pulse":    {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 180
                          },
                          "voltage":        {
                                            "type": "number",
                                            "minimum": 4.8,
                                            "maximum": 6.0
                          }
      },
      "required": ["color_scheme", "dependencies", "pin", "max_pulse","min_pulse", "abs_max_pulse","abs_min_pulse",
                   "pulse_width", "init_pulse", "voltage"]
    },

    "motor": {
      "type": "object",
      "properties": {
                          "color_scheme":  {"type": "string"},
                          "pin":           {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 31
                          },
                          "init_percentage":  {
                                            "type": "integer",
                                            "minimum": 0,
                                            "maximum": 100
                          },
                          "init_direction":{
                                            "type": "integer",
                                            "enum": [-1,0,1]
                          },
                          "pulse_width":   {
                                            "type": "integer",
                                            "minimum": 0
                          },
                          "voltage":       {
                                            "type": "number",
                                            "minimum": 6.0,
                                            "maximum": 12.0
                          }
      },
      "required": ["color_scheme", "pin", "init_percentage", "init_direction", "pulse_width", "voltage"]
    },

    "cameras":{
      "type": "object",
      "patternProperties": {"^[a-z0-9]+((_)+[a-z0-9]+)*$":{"$ref": "#/definitions/camera"}},
      "additionalProperties": false
    },

    "camera": {
      "type": "object",
      "properties": {
                          "resolution":   {
                                              "type": "string",
                                              "enum": ["1920x1080",
                                                       "3280x2464",
                                                       "3280x2464",
                                                       "1640x1232",
                                                       "1640x922",
                                                       "1280x720",
                                                       "640x480"]
                          },
                          "resolution_set":   {
                                               "type": "array",
                                               "items": {
                                                 "type": "string",
                                                 "enum": [
                                                   "1920x1080",
                                                   "3280x2464",
                                                   "3280x2464",
                                                   "1640x1232",
                                                   "1640x922",
                                                   "1280x720",
                                                   "640x480"
                                                 ]
                                               }
                          },
                          "brightness":  {
                                            "type": "number",
                                            "minimum": 0,
                                            "maximum": 100
                          },
                          "contrast":  {
                                            "type": "number",
                                            "minimum": -100,
                                            "maximum": 100
                          },
                          "sharpness":  {
                                            "type": "number",
                                            "minimum": -100,
                                            "maximum": 100
                          },
                          "saturation":  {
                                            "type": "number",
                                            "minimum": -100,
                                            "maximum": 100
                          },
                          "rotation":{
                                            "type": "integer",
                                            "enum": [0,90,180,270]
                          },
                          "hflip":         {"type": "boolean"},
                          "vflip":         {"type": "boolean"},
                          "picture_extension":  {
                                            "type": "string",
                                            "pattern": "^.(jpg|JPG)$"
                          },
                          "video_extension":  {
                                            "type": "string",
                                            "pattern": "^.(h264|H264)$"
                          },
                          "picture_path":{
                                            "type": "string",
                                            "pattern": "^(.+)/([^/]+)$"
                          },
                          "video_path":{
                                            "type": "string",
                                            "pattern": "^(.+)/([^/]+)$"
                          }
      },
      "required": ["resolution", "resolution_set", "brightness", "contrast", "sharpness", "saturation", "rotation",
                   "hflip", "vflip", "picture_extension", "video_extension", "picture_path", "video_path"]
    },

    "sensors":{
      "type": "object",
      "patternProperties": {"^[a-z0-9]+((_)+[a-z0-9]+)*$":{"$ref": "#/definitions/srf08"}},
      "additionalProperties": false
    },

    "srf08": {
      "type": "object",
      "properties": {
                          "unit":         {
                                              "type": "string",
                                              "enum": ["inches",
                                                       "centimeter",
                                                       "milliseconds"]
                          },
                          "unit_set":     {"$ref": "#/definitions/unit_set"}
      },
      "required": ["unit", "unit_set"]
    },

    "unit_set": {
      "type": "object",
      "properties": {     "inches": {
                                              "type": "string",
                                              "enum": ["0x50"]
                          },
                          "centimeter":{
                                              "type": "string",
                                              "enum": ["0x51"]
                          },
                          "milliseconds":{
                                              "type": "string",
                                              "enum": ["0x52"]
                          }
      },
      "required": ["inches", "centimeter", "milliseconds"]
    }
  },

  "type": "object",
  "properties": {
    "components":     {"$ref": "#/definitions/components"},
    "cameras":        {"$ref": "#/definitions/cameras"},
    "sensors":        {"$ref": "#/definitions/sensors"},
    "ssc32u":         {"$ref": "#/definitions/ssc32u"},
    "raspberrypi":    {"$ref": "#/definitions/raspberrypi"}
  },
  "required": ["components", "cameras", "sensors", "ssc32u", "raspberrypi"]
}

=== lincolnreese/JohnnyV/johnnyv/ext/Constants.json
{
  "components":{
    "head": {
      "servo_list": {
        "head_servo": {
          "color_scheme":     "BLACK-RED",
          "dependencies":     [],
          "pin":              29,
          "max_pulse":        180,
          "min_pulse":        0,
          "abs_max_pulse":    180,
          "abs_min_pulse":    0,
          "pulse_width":      1000,
          "init_pulse":       90,
          "voltage":          4.8
        }
      },
      "motor_list":{
      }
    },
    "left_arm": {
      "servo_list": {
        "finger_servo": {
          "color_scheme":     "WHITE",
          "dependencies":     [],
          "pin":              23,
          "max_pulse":        180,
          "min_pulse":        58,
          "abs_max_pulse":    180,
          "abs_min_pulse":    0,
          "pulse_width":      1000,
          "init_pulse":       63,
          "voltage":          4.8
        },
        "thumb_servo": {
          "color_scheme":     "GREY",
          "dependencies":     [],
          "pin":              22,
          "max_pulse":        180,
          "min_pulse":        0,
          "abs_max_pulse":    180,
          "abs_min_pulse":    0,
          "pulse_width":      1000,
          "init_pulse":       171,
          "voltage":          4.8
        },
        "wrist_servo": {
          "color_scheme":     "GREEN",
          "dependencies":     [],
          "pin":              21,
          "max_pulse":        180,
          "min_pulse":        0,
          "abs_max_pulse":    180,
          "abs_min_pulse":    0,
          "pulse_width":      1000,
          "init_pulse":       90,
          "voltage":          4.8
        },
        "upperarm_servo": {
          "color_scheme":     "BLUE",
          "dependencies":     [],
          "pin":              20,
          "max_pulse":        180,
          "min_pulse":        45,
          "abs_max_pulse":    180,
          "abs_min_pulse":    0,
          "pulse_width":      1000,
          "init_pulse":       175,
          "voltage":          4.8
        },
        "shoulder_servo": {
          "color_scheme":     "Unused",
          "dependencies":     [],
          "pin":              19,
          "max_pulse":        180,
          "min_pulse":        54,
          "abs_max_pulse":    180,
          "abs_min_pulse":    0,
          "pulse_width":      1000,
          "init_pulse":       90,
          "voltage":          4.8
        }
      },
      "motor_list": {
      }
    },
    "right_arm": {
      "servo_list": {
        "finger_servo": {
          "color_scheme":     "WHITE",
          "dependencies":     [],
          "pin":              28,
          "max_pulse":        119,
          "min_pulse":        0,
          "abs_max_pulse":    180,
          "abs_min_pulse":    0,
          "pulse_width":      1000,
          "init_pulse":       114,
          "voltage":          4.8
        },
        "thumb_servo": {
          "color_scheme":     "GREY",
          "dependencies":     [],
          "pin":              27,
          "max_pulse":        180,
          "min_pulse":        0,
          "abs_max_pulse":    180,
          "abs_min_pulse":    0,
          "pulse_width":      1000,
          "init_pulse":       9,
          "voltage":          4.8
        },
        "wrist_servo": {
          "color_scheme":     "BLUE",
          "dependencies":     [],
          "pin":              26,
          "max_pulse":        180,
          "min_pulse":        0,
          "abs_max_pulse":    180,
          "abs_min_pulse":    0,
          "pulse_width":      1000,
          "init_pulse":       90,
          "voltage":          4.8
        },
        "upperarm_servo": {
          "color_scheme":     "GREEN",
          "dependencies":     [],
          "pin":              25,
          "max_pulse":        135,
          "min_pulse":        0,
          "abs_max_pulse":    180,
          "abs_min_pulse":    0,
          "pulse_width":      1000,
          "init_pulse":       9,
          "voltage":          4.8
        },
        "shoulder_servo": {
          "color_scheme":     "RED-WHITE",
          "dependencies":     [],
          "pin":              24,
          "max_pulse":        129,
          "min_pulse":        0,
          "abs_max_pulse":    180,
          "abs_min_pulse":    0,
          "pulse_width":      1000,
          "init_pulse":       90,
          "voltage":          4.8
        }
      },
      "motor_list": {
      }
    },
    "back": {
      "servo_list": {
        "back_servo": {
          "color_scheme":     "BLACK-BLUE",
          "dependencies":     [17],
          "pin":              18,
          "max_pulse":        117,
          "min_pulse":        72,
          "abs_max_pulse":    180,
          "abs_min_pulse":    0,
          "pulse_width":      1000,
          "init_pulse":       90,
          "voltage":          4.8
        },
        "hip_servo": {
          "color_scheme":     "BLACK-GREEN",
          "dependencies":     [18],
          "pin":              17,
          "max_pulse":        108,
          "min_pulse":        72,
          "abs_max_pulse":    180,
          "abs_min_pulse":    0,
          "pulse_width":      1000,
          "init_pulse":       90,
          "voltage":          4.8
        }
      },
      "motor_list": {
      }
    },
    "base": {
      "servo_list": {
        "base_servo": {
          "color_scheme":     "BLACK-WHITE",
          "dependencies":     [],
          "pin":              16,
          "max_pulse":        162,
          "min_pulse":        18,
          "abs_max_pulse":    180,
          "abs_min_pulse":    0,
          "pulse_width":      1000,
          "init_pulse":       90,
          "voltage":          4.8
        }
      },
      "motor_list": {
      }
    },
    "track": {
      "servo_list": {
      },
      "motor_list": {
        "forward":{
          "color_scheme":     "UNUSED",
          "pin":              30,
          "init_percentage":  0,
          "init_direction":   0,
          "pulse_width":      1000,
          "voltage":          12.0
        },
        "turn":{
          "color_scheme":     "UNUSED2",
          "pin":              31,
          "init_percentage":  0,
          "init_direction":   0,
          "pulse_width":      1000,
          "voltage":          12.0
        }
      }
    }
  },
  "cameras":{
    "noirv2":{
        "resolution":         "1280x720",
        "resolution_set":     ["1920x1080",
                               "3280x2464",
                               "3280x2464",
                               "1640x1232",
                               "1640x922",
                               "1280x720",
                               "640x480"],
        "brightness":         50,
        "contrast":           0,
        "sharpness":          0,
        "saturation":         0,
        "rotation":           0,
        "hflip":              false,
        "vflip":              false,
        "picture_extension":  ".jpg",
        "video_extension":    ".h264",
        "picture_path":       "/johnny5/pictures",
        "video_path":         "/johnny5/videos"
    }
  },
  "sensors":{
    "srf08":{
      "unit":                 "centimeter",
      "unit_set":{
        "inches":             "0x50",
        "centimeter":         "0x51",
        "milliseconds":       "0x52"
      }
    }
  },
  "ssc32u": {
    "baud":                   9600,
    "timeout":                1.0,
    "execution_time":         1,
    "voltage":                7.4
  },
  "raspberrypi": {
    "ip":                    "192.168.2.1",
    "username":              "admin",
    "password":              "1234"
  }
}
